[DEFAULT]

# Filename Specifications:
input_filename = /home/al3926/regrid/input/fullTorus.vtk
output_filename_vtk = /home/al3926/regrid/output/regrid_fullTorus.vtk
output_filename_vdb = /home/al3926/regrid/output/regrid_fullTorus.vdb

# Phi Normalization for OpenVDB:
# If 0, the phi values will be exact.
# If 1, the phi values will use a normalized magnitude range from 0.0 to 1.0.
vdb_normalization = 0

# Resolution (X:Y:Z):
# Each dimension must be greater than 1.
# The following resolutions are specific to the tokamak model in the "input" directory.
# Disk:       Low = 18:23:2      Medium = 35:46:2        High = 70:92:2        Very High = 140:184:2
# Quarter:    Low = 48:23:43     Medium = 96:46:85       High = 192:92:170     Very High = 384:184:340
# Half:       Low = 85:23:43     Medium = 170:46:85      High = 340:92:170     Very High = 680:184:340
# Full:       Low = 85:23:85     Medium = 170:46:170     High = 340:92:340     Very High = 680:184:680
X = 170
Y = 46
Z = 170